[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
